CC=g++
CFLAGS=-std=c++17

probing: 
	$(CC) $(CFLAGS) -o probing runner_probing.cpp Hash.cpp ProbingHashTable.cpp

chaining:
	$(CC) $(CFLAGS) -o chaining runner_chaining.cpp Hash.cpp ChainingHashTable.cpp

CoolCoin:
	$(CC) $(CFLAGS) -o CoolCoin CoolCoin.cpp Hash.cpp